package ru.stroy1click.catalog.model;

public enum MessageType {

    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED,
    SUBCATEGORY_CREATED,
    SUBCATEGORY_UPDATED,
    SUBCATEGORY_DELETED,
    PRODUCT_TYPE_CREATED,
    PRODUCT_TYPE_UPDATED,
    PRODUCT_TYPE_DELETED,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED
}
