CREATE SCHEMA IF NOT EXISTS product;

CREATE TABLE IF NOT EXISTS product.categories
(
    id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(40) NOT NULL UNIQUE,
    image VARCHAR
);

CREATE TABLE IF NOT EXISTS product.subcategories
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INT REFERENCES product.categories (id) ON DELETE CASCADE,
    title       VARCHAR(40) NOT NULL,
    image       VARCHAR
);

CREATE TABLE IF NOT EXISTS product.product_types
(
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcategory_id INT REFERENCES product.subcategories (id) ON DELETE CASCADE,
    title          VARCHAR(40) NOT NULL,
    image          VARCHAR
);

CREATE TABLE IF NOT EXISTS product.products
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(60) NOT NULL,
    description     VARCHAR(1000),
    price           FLOAT       NOT NULL,
    in_stock        BOOLEAN     NOT NULL,
    category_id     INT REFERENCES product.categories (id) ON DELETE CASCADE,
    subcategory_id  INT REFERENCES product.subcategories (id) ON DELETE CASCADE,
    product_type_id INT REFERENCES product.product_types (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS product.attributes
(
    id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS product.product_attribute_values
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value        VARCHAR(40) NOT NULL,
    attribute_id INT REFERENCES product.attributes (id) ON DELETE CASCADE,
    product_id   INT REFERENCES product.products (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS product.product_type_attribute_values
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value           VARCHAR(40) NOT NULL,
    attribute_id    INT REFERENCES product.attributes (id) ON DELETE CASCADE,
    product_type_id INT REFERENCES product.product_types (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS product.product_images
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT REFERENCES product.products (id) ON DELETE CASCADE,
    link       VARCHAR
);

--- 1 - get
--- 2 - update
--- 3 - delete Не ставить в REFERENCES

-- ---------- Categories ----------
-- Test: CategoryTests get()
-- Описание: категория для проверки метода получения категории
INSERT INTO product.categories (title, image) VALUES ('Water', 'water.png');

-- Test: CategoryTests update()
-- Описание: категория для проверки метода обновления
INSERT INTO product.categories (title, image) VALUES ('Milk', 'milk.png');

-- Test: CategoryTests delete()
-- Описание: категория для проверки метода удаления
INSERT INTO product.categories (title, image) VALUES ('Cheese', 'cheese.png');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('product.categories_id_seq', (SELECT MAX(id) FROM product.categories));

-- ---------- Subcategories ----------
-- Test: SubcategoryTests get()
-- Описание: подкатегория для проверки метода получения подкатегории
INSERT INTO product.subcategories (category_id, title, image) VALUES
    (1, 'T-shirts', 'tshirts.png');

-- Test: SubcategoryTests create()
-- Описание: подкатегория для проверки метода создания
INSERT INTO product.subcategories (category_id, title, image) VALUES
    (1, 'Cheese', 'cheese.png');

-- Test: SubcategoryTests update()
-- Описание: подкатегория для проверки метода обновления
INSERT INTO product.subcategories (category_id, title, image) VALUES
    (1, 'Milk Products', 'milk_products.png');

-- Test: SubcategoryTests delete()
-- Описание: подкатегория для проверки метода удаления
INSERT INTO product.subcategories (category_id, title, image) VALUES
    (2, 'Fruits', 'fruits.png');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('product.subcategories_id_seq', (SELECT MAX(id) FROM product.subcategories));

-- Test: ProductTypeTests get()
-- Описание: получение типа продукта по id
INSERT INTO product.product_types (subcategory_id, title, image) VALUES
    (1, 'Orange T-Shirt', 'orange_tshirt.png');

-- Test: ProductTypeTests update()
-- Описание: обновление типа продукта
INSERT INTO product.product_types (subcategory_id, title, image) VALUES
    (1, 'Blue T-Shirt', 'blue_tshirt.png');

-- Test: ProductTypeTests delete()
-- Описание: удаление типа продукта
INSERT INTO product.product_types (subcategory_id, title, image) VALUES
    (1, 'Green T-Shirt', 'green_tshirt.png');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('product.product_types_id_seq', (SELECT MAX(id) FROM product.product_types));


-- ---------- Products ----------
-- Test: ProductTests get()
-- Описание: продукт для проверки получения по id
INSERT INTO product.products (id,category_id, subcategory_id, product_type_id, title, description, price, in_stock)
VALUES (1,1,1, 1, 'First Product', 'Description of first product', 100.00, true);

-- Test: ProductTests update()
-- Описание: продукт для проверки метода обновления
INSERT INTO product.products (id,category_id, subcategory_id, product_type_id, title, description, price, in_stock)
VALUES (2, 1,1, 1, 'Second Product', 'Description of second product', 150.00, true);

-- Test: ProductTests delete()
-- Описание: продукт для проверки метода удаления
INSERT INTO product.products (id,category_id, subcategory_id, product_type_id, title, description, price, in_stock)
VALUES (3, 1,1, 1, 'Third Product', 'Description of third product', 200.00, true);

-- Синхронизируем sequence с текущим max(id)
SELECT setval('product.products_id_seq', (SELECT MAX(id) FROM product.products));

-- ---------- Attributes ----------

-- Test: AttributeTests get()
-- Описание: атрибут для проверки метода получения по id
INSERT INTO product.attributes (title) VALUES('Color');

-- Test: AttributeTests update()
-- Описание: атрибут для проверки метода обновления
INSERT INTO product.attributes (title) VALUES('Size');

-- Test: AttributeTests delete()
-- Описание: атрибут для проверки метода удаления
INSERT INTO product.attributes (title) VALUES('Material');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('product.attributes_id_seq', (SELECT MAX(id) FROM product.attributes));


-- ---------- Product Attribute Values ----------

-- Test: ProductAttributeValueTests get()
-- Описание: значение атрибута продукта для проверки метода получения по id
INSERT INTO product.product_attribute_values (attribute_id, product_id, value) VALUES
    (1, 1, 'Red');

-- Test: ProductAttributeValueTests update()
-- Описание: значение атрибута продукта для проверки метода обновления
INSERT INTO product.product_attribute_values (attribute_id, product_id, value) VALUES
    (2, 1, 'Medium');

-- Test: ProductAttributeValueTests delete()
-- Описание: значение атрибута продукта для проверки метода удаления
INSERT INTO product.product_attribute_values (attribute_id, product_id, value) VALUES
    (2, 2, 'Cotton');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('product.product_attribute_values_id_seq', (SELECT MAX(id) FROM product.product_attribute_values));

-- ---------- Product Type Attribute Values ----------

-- Test: ProductTypeAttributeValueTests get_ShouldReturnProductTypeAttributeValue_WhenValueExists
-- Описание: значение атрибута типа продукта для проверки получения
INSERT INTO product.product_type_attribute_values (attribute_id, product_type_id, value)
VALUES (1, 1, 'Size');

-- Test: ProductTypeAttributeValueTests update_ShouldUpdateProductTypeAttributeValue_WhenDtoIsValid
-- Описание: значение атрибута типа продукта для проверки обновления
INSERT INTO product.product_type_attribute_values (attribute_id, product_type_id, value)
VALUES (1, 1, 'Color');

-- Test: ProductTypeAttributeValueTests delete_ShouldDeleteProductTypeAttributeValue_WhenValueExists
-- Описание: значение атрибута типа продукта для проверки удаления
INSERT INTO product.product_type_attribute_values (attribute_id, product_type_id, value)
VALUES (1, 1, 'Material');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('product.product_type_attribute_values_id_seq', (SELECT MAX(id) FROM product.product_type_attribute_values));