create schema if not exists product;

create table if not exists product.categories
(
    id int generated by default as identity primary key ,
    title varchar(40) not null unique,
    image varchar
);

create table if not exists product.subcategories(
                                                    id int generated by default as identity primary key ,
                                                    category_id int references product.categories(id) on delete cascade,
                                                    title varchar(40) not null,
                                                    image varchar
);

create table if not exists product.product_types(
                                                    id int generated by default as identity primary key ,
                                                    subcategory_id int references product.subcategories(id) on delete cascade ,
                                                    title varchar(40) not null,
                                                    image varchar
);

create table if not exists product.outbox_message(
                                                     id bigint generated by default as identity primary key ,
                                                     payload varchar not null ,
                                                     status varchar not null ,
                                                     type varchar not null,
                                                     created_at timestamp not null ,
                                                     error_message varchar ,
                                                     retry_attempts int not null
);

create table if not exists product.products(
                                               id int generated by default as identity primary key ,
                                               title varchar(60) not null ,
                                               description varchar(1000) ,
                                               price float not null ,
                                               in_stock boolean not null,
                                               category_id int references product.categories(id) on delete cascade,
                                               subcategory_id int references product.subcategories(id) on delete cascade,
                                               product_type_id int references product.product_types(id) on delete cascade
);

create table if not exists product.attributes(
                                                 id int generated by default as identity primary key ,
                                                 title varchar(40) not null
);

create table if not exists product.product_attribute_values(
                                                               id int generated by default as identity primary key ,
                                                               value varchar(40) not null ,
                                                               attribute_id int references product.attributes(id) on delete cascade ,
                                                               product_id int references product.products(id) on delete cascade
);


create table if not exists product.product_type_attribute_values(
                                                                    id int generated by default as identity primary key ,
                                                                    value varchar(40) not null ,
                                                                    attribute_id int references product.attributes(id) on delete cascade ,
                                                                    product_type_id int references product.product_types(id) on delete cascade
);

create table if not exists product.product_images(
                                                     id int generated by default as identity primary key ,
                                                     product_id int references product.products(id) on delete cascade ,
                                                     link varchar
);

--- 1 - get
--- 2 - update
--- 3 - delete Не ставить в REFERENCES

-- ---------- Categories ----------
-- Test: CategoryTests get()
-- Описание: категория для проверки метода получения категории
INSERT INTO product.categories (title, image) VALUES ('Water', 'water.png');

-- Test: CategoryTests update()
-- Описание: категория для проверки метода обновления
INSERT INTO product.categories (title, image) VALUES ('Milk', 'milk.png');

-- Test: CategoryTests delete()
-- Описание: категория для проверки метода удаления
INSERT INTO product.categories (title, image) VALUES ('Cheese', 'cheese.png');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('product.categories_id_seq', (SELECT MAX(id) FROM product.categories));

-- ---------- Subcategories ----------
-- Test: SubcategoryTests get()
-- Описание: подкатегория для проверки метода получения подкатегории
INSERT INTO product.subcategories (category_id, title, image) VALUES
    (1, 'T-shirts', 'tshirts.png');

-- Test: SubcategoryTests create()
-- Описание: подкатегория для проверки метода создания
INSERT INTO product.subcategories (category_id, title, image) VALUES
    (1, 'Cheese', 'cheese.png');

-- Test: SubcategoryTests update()
-- Описание: подкатегория для проверки метода обновления
INSERT INTO product.subcategories (category_id, title, image) VALUES
    (1, 'Milk Products', 'milk_products.png');

-- Test: SubcategoryTests delete()
-- Описание: подкатегория для проверки метода удаления
INSERT INTO product.subcategories (category_id, title, image) VALUES
    (2, 'Fruits', 'fruits.png');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('product.subcategories_id_seq', (SELECT MAX(id) FROM product.subcategories));

-- Test: ProductTypeTests get()
-- Описание: получение типа продукта по id
INSERT INTO product.product_types (subcategory_id, title, image) VALUES
    (1, 'Orange T-Shirt', 'orange_tshirt.png');

-- Test: ProductTypeTests update()
-- Описание: обновление типа продукта
INSERT INTO product.product_types (subcategory_id, title, image) VALUES
    (1, 'Blue T-Shirt', 'blue_tshirt.png');

-- Test: ProductTypeTests delete()
-- Описание: удаление типа продукта
INSERT INTO product.product_types (subcategory_id, title, image) VALUES
    (1, 'Green T-Shirt', 'green_tshirt.png');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('product.product_types_id_seq', (SELECT MAX(id) FROM product.product_types));


-- ---------- Products ----------
-- Test: ProductTests get()
-- Описание: продукт для проверки получения по id
INSERT INTO product.products (id,category_id, subcategory_id, product_type_id, title, description, price, in_stock)
VALUES (1,1,1, 1, 'First Product', 'Description of first product', 100.00, true);

-- Test: ProductTests update()
-- Описание: продукт для проверки метода обновления
INSERT INTO product.products (id,category_id, subcategory_id, product_type_id, title, description, price, in_stock)
VALUES (2, 1,1, 1, 'Second Product', 'Description of second product', 150.00, true);

-- Test: ProductTests delete()
-- Описание: продукт для проверки метода удаления
INSERT INTO product.products (id,category_id, subcategory_id, product_type_id, title, description, price, in_stock)
VALUES (3, 1,1, 1, 'Third Product', 'Description of third product', 200.00, true);

-- Синхронизируем sequence с текущим max(id)
SELECT setval('product.products_id_seq', (SELECT MAX(id) FROM product.products));

-- ---------- Attributes ----------

-- Test: AttributeTests get()
-- Описание: атрибут для проверки метода получения по id
INSERT INTO product.attributes (title) VALUES('Color');

-- Test: AttributeTests update()
-- Описание: атрибут для проверки метода обновления
INSERT INTO product.attributes (title) VALUES('Size');

-- Test: AttributeTests delete()
-- Описание: атрибут для проверки метода удаления
INSERT INTO product.attributes (title) VALUES('Material');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('product.attributes_id_seq', (SELECT MAX(id) FROM product.attributes));


-- ---------- Product Attribute Values ----------

-- Test: ProductAttributeValueTests get()
-- Описание: значение атрибута продукта для проверки метода получения по id
INSERT INTO product.product_attribute_values (attribute_id, product_id, value) VALUES
    (1, 1, 'Red');

-- Test: ProductAttributeValueTests update()
-- Описание: значение атрибута продукта для проверки метода обновления
INSERT INTO product.product_attribute_values (attribute_id, product_id, value) VALUES
    (2, 1, 'Medium');

-- Test: ProductAttributeValueTests delete()
-- Описание: значение атрибута продукта для проверки метода удаления
INSERT INTO product.product_attribute_values (attribute_id, product_id, value) VALUES
    (2, 2, 'Cotton');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('product.product_attribute_values_id_seq', (SELECT MAX(id) FROM product.product_attribute_values));

-- ---------- Product Type Attribute Values ----------

-- Test: ProductTypeAttributeValueTests get_ShouldReturnProductTypeAttributeValue_WhenValueExists
-- Описание: значение атрибута типа продукта для проверки получения
INSERT INTO product.product_type_attribute_values (attribute_id, product_type_id, value)
VALUES (1, 1, 'Size');

-- Test: ProductTypeAttributeValueTests update_ShouldUpdateProductTypeAttributeValue_WhenDtoIsValid
-- Описание: значение атрибута типа продукта для проверки обновления
INSERT INTO product.product_type_attribute_values (attribute_id, product_type_id, value)
VALUES (1, 1, 'Color');

-- Test: ProductTypeAttributeValueTests delete_ShouldDeleteProductTypeAttributeValue_WhenValueExists
-- Описание: значение атрибута типа продукта для проверки удаления
INSERT INTO product.product_type_attribute_values (attribute_id, product_type_id, value)
VALUES (1, 1, 'Material');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('product.product_type_attribute_values_id_seq', (SELECT MAX(id) FROM product.product_type_attribute_values));