create schema if not exists catalog;

create table if not exists catalog.categories
(
    id int generated by default as identity primary key ,
    title varchar(40) not null unique,
    image varchar
);

create table if not exists catalog.subcategories(
    id int generated by default as identity primary key ,
    category_id int references catalog.categories(id) on delete cascade,
    title varchar(40) not null,
    image varchar
);

create table if not exists catalog.product_types(
    id int generated by default as identity primary key ,
    subcategory_id int references catalog.subcategories(id) on delete cascade ,
    title varchar(40) not null,
    image varchar
);

create table if not exists catalog.outbox_message(
    id bigint generated by default as identity primary key ,
    payload varchar not null ,
    status varchar not null ,
    type varchar not null,
    created_at timestamp not null ,
    error_message varchar ,
    retry_attempts int not null
);

create table if not exists catalog.products(
    id int generated by default as identity primary key ,
    title varchar(60) not null ,
    description varchar(1000) ,
    price float not null ,
    in_stock boolean not null,
    category_id int references catalog.categories(id) on delete cascade,
    subcategory_id int references catalog.subcategories(id) on delete cascade,
    product_type_id int references catalog.product_types(id) on delete cascade
);

create table if not exists catalog.product_images(
    id int generated by default as identity primary key ,
    product_id int references catalog.products(id) on delete cascade ,
    link varchar
);

--- 1 - get
--- 2 - update
--- 3 - delete Не ставить в REFERENCES

-- ---------- Categories ----------
-- Test: CategoryTests get()
-- Описание: категория для проверки метода получения категории
INSERT INTO catalog.categories (title, image) VALUES ('Water', 'water.png');

-- Test: CategoryTests update()
-- Описание: категория для проверки метода обновления
INSERT INTO catalog.categories (title, image) VALUES ('Milk', 'milk.png');

-- Test: CategoryTests delete()
-- Описание: категория для проверки метода удаления
INSERT INTO catalog.categories (title, image) VALUES ('Cheese', 'cheese.png');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('catalog.categories_id_seq', (SELECT MAX(id) FROM catalog.categories));

-- ---------- Subcategories ----------
-- Test: SubcategoryTests get()
-- Описание: подкатегория для проверки метода получения подкатегории
INSERT INTO catalog.subcategories (category_id, title, image) VALUES
    (1, 'T-shirts', 'tshirts.png');

-- Test: SubcategoryTests create()
-- Описание: подкатегория для проверки метода создания
INSERT INTO catalog.subcategories (category_id, title, image) VALUES
    (1, 'Cheese', 'cheese.png');

-- Test: SubcategoryTests update()
-- Описание: подкатегория для проверки метода обновления
INSERT INTO catalog.subcategories (category_id, title, image) VALUES
    (1, 'Milk Products', 'milk_products.png');

-- Test: SubcategoryTests delete()
-- Описание: подкатегория для проверки метода удаления
INSERT INTO catalog.subcategories (category_id, title, image) VALUES
    (2, 'Fruits', 'fruits.png');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('catalog.subcategories_id_seq', (SELECT MAX(id) FROM catalog.subcategories));

-- Test: ProductTypeTests get()
-- Описание: получение типа продукта по id
INSERT INTO catalog.product_types (subcategory_id, title, image) VALUES
    (1, 'Orange T-Shirt', 'orange_tshirt.png');

-- Test: ProductTypeTests update()
-- Описание: обновление типа продукта
INSERT INTO catalog.product_types (subcategory_id, title, image) VALUES
    (1, 'Blue T-Shirt', 'blue_tshirt.png');

-- Test: ProductTypeTests delete()
-- Описание: удаление типа продукта
INSERT INTO catalog.product_types (subcategory_id, title, image) VALUES
    (1, 'Green T-Shirt', 'green_tshirt.png');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('catalog.product_types_id_seq', (SELECT MAX(id) FROM catalog.product_types));


-- ---------- Products ----------
-- Test: ProductTests get()
-- Описание: продукт для проверки получения по id
INSERT INTO catalog.products (id,category_id, subcategory_id, product_type_id, title, description, price, in_stock)
VALUES (1,1,1, 1, 'First Product', 'Description of first product', 100.00, true);

-- Test: ProductTests update()
-- Описание: продукт для проверки метода обновления
INSERT INTO catalog.products (id,category_id, subcategory_id, product_type_id, title, description, price, in_stock)
VALUES (2, 1,1, 1, 'Second Product', 'Description of second product', 150.00, true);

-- Test: ProductTests delete()
-- Описание: продукт для проверки метода удаления
INSERT INTO catalog.products (id,category_id, subcategory_id, product_type_id, title, description, price, in_stock)
VALUES (3, 1,1, 1, 'Third Product', 'Description of third product', 200.00, true);

-- Синхронизируем sequence с текущим max(id)
SELECT setval('catalog.products_id_seq', (SELECT MAX(id) FROM catalog.products));