create schema if not exists catalog;

create table if not exists catalog.categories
(
    id int generated by default as identity primary key ,
    title varchar(40) not null unique,
    image varchar
);

create table if not exists catalog.subcategories(
    id int generated by default as identity primary key ,
    category_id int references catalog.categories(id) on delete cascade,
    title varchar(40) not null,
    image varchar
);

create table if not exists catalog.product_types(
    id int generated by default as identity primary key ,
    subcategory_id int references catalog.subcategories(id) on delete cascade ,
    title varchar(40) not null,
    image varchar
);

create table if not exists catalog.outbox_message(
    id bigint generated by default as identity primary key ,
    payload varchar not null ,
    status varchar not null ,
    type varchar not null,
    created_at timestamp not null ,
    error_message varchar ,
    retry_attempts int not null
);

create table if not exists catalog.products(
    id int generated by default as identity primary key ,
    title varchar(60) not null ,
    description varchar(1000) ,
    price float not null ,
    in_stock boolean not null,
    category_id int references catalog.categories(id) on delete cascade,
    subcategory_id int references catalog.subcategories(id) on delete cascade,
    product_type_id int references catalog.product_types(id) on delete cascade
);

create table if not exists catalog.product_images(
    id int generated by default as identity primary key ,
    product_id int references catalog.products(id) on delete cascade ,
    link varchar
);