create schema if not exists product;

create table if not exists product.categories
(
    id int generated by default as identity primary key ,
    title varchar(40) not null unique,
    image varchar
);

create table if not exists product.subcategories(
    id int generated by default as identity primary key ,
    category_id int references product.categories(id) on delete cascade,
    title varchar(40) not null,
    image varchar
);

create table if not exists product.product_types(
    id int generated by default as identity primary key ,
    subcategory_id int references product.subcategories(id) on delete cascade ,
    title varchar(40) not null,
    image varchar
);

create table if not exists product.outbox_message(
    id bigint generated by default as identity primary key ,
    payload varchar not null ,
    status varchar not null ,
    type varchar not null,
    created_at timestamp not null ,
    error_message varchar ,
    retry_attempts int not null
);

create table if not exists product.products(
    id int generated by default as identity primary key ,
    title varchar(60) not null ,
    description varchar(1000) ,
    price float not null ,
    in_stock boolean not null,
    category_id int references product.categories(id) on delete cascade,
    subcategory_id int references product.subcategories(id) on delete cascade,
    product_type_id int references product.product_types(id) on delete cascade
);

create table if not exists product.attributes(
    id int generated by default as identity primary key ,
    title varchar(40) not null
);

create table if not exists product.product_attribute_values(
    id int generated by default as identity primary key ,
    value varchar(40) not null ,
    attribute_id int references product.attributes(id) on delete cascade ,
    product_id int references product.products(id) on delete cascade
);


create table if not exists product.product_type_attribute_values(
    id int generated by default as identity primary key ,
    value varchar(40) not null ,
    attribute_id int references product.attributes(id) on delete cascade ,
    product_type_id int references product.product_types(id) on delete cascade
);

create table if not exists product.product_images(
    id int generated by default as identity primary key ,
    product_id int references product.products(id) on delete cascade ,
    link varchar
);